
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";



import { StackHandlerRoutes, LoginRedirect } from "app/auth";


import App from "./pages/App.tsx";
import Asetukset from "./pages/Asetukset.tsx";
import HallintaKäyttäjät from "./pages/HallintaKäyttäjät.tsx";
import Huoltohistoria from "./pages/Huoltohistoria.tsx";
import Investointisuunnitelma from "./pages/Investointisuunnitelma.tsx";
import Kayttoehdot from "./pages/Kayttoehdot.tsx";
import Kuntoarviot from "./pages/Kuntoarviot.tsx";
import Mobiilitarkastus from "./pages/Mobiilitarkastus.tsx";
import Portfolio from "./pages/Portfolio.tsx";
import PortfolioYhteenveto from "./pages/PortfolioYhteenveto.tsx";
import RakennuksenTiedot from "./pages/RakennuksenTiedot.tsx";
import Rakennukset from "./pages/Rakennukset.tsx";
import Tietosuoja from "./pages/Tietosuoja.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/", element: <App /> },
	{ path: "/asetukset", element: <Asetukset /> },
	{ path: "/hallinta-käyttäjät", element: <HallintaKäyttäjät /> },
	{ path: "/hallintakäyttäjät", element: <HallintaKäyttäjät /> },
	{ path: "/huoltohistoria", element: <Huoltohistoria /> },
	{ path: "/investointisuunnitelma", element: <Investointisuunnitelma /> },
	{ path: "/kayttoehdot", element: <Kayttoehdot /> },
	{ path: "/kuntoarviot", element: <Kuntoarviot /> },
	{ path: "/mobiilitarkastus", element: <Mobiilitarkastus /> },
	{ path: "/portfolio", element: <Portfolio /> },
	{ path: "/portfolio-yhteenveto", element: <PortfolioYhteenveto /> },
	{ path: "/portfolioyhteenveto", element: <PortfolioYhteenveto /> },
	{ path: "/rakennuksen-tiedot", element: <RakennuksenTiedot /> },
	{ path: "/rakennuksentiedot", element: <RakennuksenTiedot /> },
	{ path: "/rakennukset", element: <Rakennukset /> },
	{ path: "/tietosuoja", element: <Tietosuoja /> },

];
